version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
