# -----------------------------------------------------------------------------
# RBAC for app-secrets: Enterprise-Grade, Least Privilege
# -----------------------------------------------------------------------------
# This policy ensures that only the orchestrator-api and data-worker pods can
# access the app-secrets Secret. It uses dedicated ServiceAccounts, Roles, and
# RoleBindings for least privilege and future extensibility.
# -----------------------------------------------------------------------------

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator-api-sa
  labels:
    app: orchestrator-api

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-worker-sa
  labels:
    app: data-worker

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-secrets-reader
  labels:
    app: salescience
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["app-secrets"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestrator-api-secrets-access
  labels:
    app: orchestrator-api
subjects:
  - kind: ServiceAccount
    name: orchestrator-api-sa
    namespace: default
roleRef:
  kind: Role
  name: app-secrets-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-worker-secrets-access
  labels:
    app: data-worker
subjects:
  - kind: ServiceAccount
    name: data-worker-sa
    namespace: default
roleRef:
  kind: Role
  name: app-secrets-reader
  apiGroup: rbac.authorization.k8s.io 