apiVersion: v1
kind: Service
metadata:
  name: orchestrator-api
  labels:
    app: orchestrator-api
spec:
  type: ClusterIP
  selector:
    app: orchestrator-api
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100 