apiVersion: v1
kind: Service
metadata:
  name: data-worker
  labels:
    app: data-worker
spec:
  type: ClusterIP
  selector:
    app: data-worker
  # No ports needed unless other services need to talk to the worker directly 