# worker-deployment.yaml
# ----------------------
# Kubernetes Deployment manifest for Data Acquisition Worker
# - Runs the async/concurrent worker
# - Resource requests/limits for stability
# - Liveness/readiness probes for health monitoring
# - Pod anti-affinity for high availability
# - Environment variables from ConfigMap/Secret
#
# Apply with: kubectl apply -f kubernetes/worker-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-worker
  labels:
    app: data-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-worker
  template:
    metadata:
      labels:
        app: data-worker
      annotations:
        sidecar.istio.io/inject: "true"  # Enable Istio sidecar injection
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - data-worker
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: data-worker
          image: yourrepo/data-worker:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem: false 